import type { SpawnPoints } from "../../src/world/tiles.ts"

const MARKER_START = "// @map-editor:start"
const MARKER_END = "// @map-editor:end"

export interface MapData {
  tiles: number[][]
  spawnPoints: SpawnPoints
}

function extractBlock(content: string): string | null {
  const startIdx = content.indexOf(MARKER_START)
  const endIdx = content.indexOf(MARKER_END)
  if (startIdx === -1 || endIdx === -1) return null
  return content.slice(startIdx + MARKER_START.length, endIdx)
}

/**
 * Find the end index of a bracket-balanced value starting at startIdx.
 * startIdx must point at `[` or `{`. Returns the index of the matching `]` or `}`.
 */
function findMatchingBracket(
  str: string,
  startIdx: number,
): number | null {
  const open = str[startIdx]
  const close = open === "[" ? "]" : "}"
  let depth = 1
  for (let i = startIdx + 1; i < str.length; i++) {
    const c = str[i]
    if (c === open) depth++
    else if (c === close) {
      depth--
      if (depth === 0) return i
    }
  }
  return null
}

/**
 * Parse tiles and spawn points from between the @map-editor markers.
 * Returns null if markers are absent.
 * Handles multiline arrays and objects — uses bracket matching, not regex.
 */
export function parseSceneFile(content: string): MapData | null {
  const block = extractBlock(content)
  if (block === null) return null

  const tilesStart = block.indexOf("TILES")
  const spawnStart = block.indexOf("SPAWN_POINTS")
  if (tilesStart === -1 || spawnStart === -1) return null

  const tilesValueStart = block.indexOf("[", tilesStart)
  const spawnValueStart = block.indexOf("{", spawnStart)
  if (tilesValueStart === -1 || spawnValueStart === -1) return null

  const tilesEnd = findMatchingBracket(block, tilesValueStart)
  const spawnEnd = findMatchingBracket(block, spawnValueStart)
  if (tilesEnd === null || spawnEnd === null) return null

  const tilesJson = block.slice(tilesValueStart, tilesEnd + 1)
  const spawnJson = block.slice(spawnValueStart, spawnEnd + 1)

  try {
    return {
      tiles: JSON.parse(tilesJson) as number[][],
      spawnPoints: JSON.parse(spawnJson) as Record<
        string,
        { x: number; y: number }
      >,
    }
  } catch {
    return null
  }
}

/**
 * Serialize map data into the TypeScript lines that go between the markers.
 * The output is valid TypeScript and round-trips cleanly through parseSceneFile.
 */
export function serializeSceneBlock(data: MapData): string {
  const tilesJson = JSON.stringify(data.tiles)
  const spawnJson = JSON.stringify(data.spawnPoints)
  return [
    "",
    `export const TILES = ${tilesJson} as number[][];`,
    `export const SPAWN_POINTS = ${spawnJson} as Record<string, { x: number; y: number }>;`,
    "",
  ].join("\n")
}

/**
 * Replace the block between the markers with newBlock.
 * Content outside the markers is preserved exactly.
 * Returns null if markers are absent.
 */
export function replaceMarkerBlock(
  content: string,
  newBlock: string,
): string | null {
  const startIdx = content.indexOf(MARKER_START)
  const endIdx = content.indexOf(MARKER_END)
  if (startIdx === -1 || endIdx === -1) return null
  return (
    content.slice(0, startIdx + MARKER_START.length) +
    newBlock +
    content.slice(endIdx)
  )
}

/**
 * Extract the list of scene names from the SCENE_NAMES array in worldGraph.ts.
 * Returns an empty array if the array is not found.
 */
export function parseSceneNames(content: string): string[] {
  const match = content.match(/SCENE_NAMES\s*=\s*\[([^\]]*)\]/)
  if (!match) return []
  return [...match[1].matchAll(/['"]([^'"]+)['"]/g)].map((m) => m[1])
}

/**
 * Scaffold a minimal map file with the marker block, an all-zero tile array,
 * and empty spawn points. The developer fills in the Tilemap definition below the markers.
 */
export function scaffoldSceneFile(width: number, height: number): string {
  const tiles = Array.from({ length: height }, () =>
    Array<number>(width).fill(0),
  )
  const block = serializeSceneBlock({ tiles, spawnPoints: {} })
  return [
    "// Generated by map editor — add Tilemap definition and imports below.",
    "",
    MARKER_START,
    block,
    MARKER_END,
    "",
  ].join("\n")
}

/**
 * Resize a tile grid to new dimensions.
 * Expanding: new cells filled with `fill` (default 0).
 * Shrinking: excess rows/columns truncated.
 */
export function resizeTileGrid(
  tiles: number[][],
  newWidth: number,
  newHeight: number,
  fill = 0,
): number[][] {
  return Array.from({ length: newHeight }, (_, row) =>
    Array.from({ length: newWidth }, (_, col) => tiles[row]?.[col] ?? fill),
  )
}

/**
 * Append a new scene name to the SCENE_NAMES array in worldGraph.ts source.
 * Preserves all content outside the array.
 */
export function addSceneName(content: string, name: string): string {
  return content.replace(
    /(SCENE_NAMES\s*=\s*\[)([^\]]*)(\])/,
    (_, open: string, items: string, close: string) => {
      const trimmed = items.trim()
      const newItem = `'${name}'`
      const updated = trimmed === "" ? newItem : `${trimmed}, ${newItem}`
      return `${open}${updated}${close}`
    },
  )
}
