// editor/server/tileWriter.ts
// Pure functions for generating tiles.ts source and tilesheet PNG from tile registry data.
// No file I/O here — callers handle reading and writing.

import { PNG } from "pngjs"
import type { TileDefinition } from "../../src/world/tiles.ts"

// Pixel data for one terrain type: array of frames, each frame is a flat
// RGBA array of SPRITE_TILE_SIZE × SPRITE_TILE_SIZE × 4 values (0–255).
export type FramePixelData = Record<string, number[][]>

const SPRITE_TILE_SIZE = 16

// ---------------------------------------------------------------------------
// generateTilesTs

// Serialises a BlobFrameSet (16 entries) as inline object literal.
function serializeFrames(frames: TileDefinition["frames"]): string {
  return (
    "{\n" +
    Array.from({ length: 16 }, (_, mask) => {
      const f = frames[mask] ?? { frameIndex: 0, flipX: false, flipY: false }
      return `      ${mask}: { frameIndex: ${f.frameIndex}, flipX: ${f.flipX}, flipY: ${f.flipY} }`
    }).join(",\n") +
    ",\n    }"
  )
}

// Produces a fully valid src/world/tiles.ts from the given registry.
// The file is self-contained — all type definitions, the registry, and getTileById are included.
export function generateTilesTs(registry: readonly TileDefinition[]): string {
  const tileTypeUnion = registry.map((t) => `"${t.type}"`).join(" | ")

  const registryEntries = registry
    .map(
      (t) => `  {
    id: ${t.id},
    type: "${t.type}",
    name: "${t.name}",
    solid: ${t.solid},
    editorColour: "${t.editorColour}",
    frames: ${serializeFrames(t.frames)},
    baseCoords: { col: ${t.baseCoords.col}, row: ${t.baseCoords.row} },
  }`,
    )
    .join(",\n")

  return `// src/world/tiles.ts
// Generated by the tile editor — see documents/tile-editor-spec.md.
// Do not edit by hand; use the tile editor to update tile types and blob rulesets.

export const SPRITE_TILE_SIZE = ${SPRITE_TILE_SIZE}

export type TileType = ${tileTypeUnion}

export interface BlobFrame {
  frameIndex: number
  flipX: boolean
  flipY: boolean
}

// Full cardinal blob ruleset. Keys 0–15: 4-bit bitmask (bit0=N, bit1=E, bit2=S, bit3=W).
export type BlobFrameSet = Record<number, BlobFrame>

// Grid-unit location on the tilesheet (multiply by SPRITE_TILE_SIZE for pixels).
export interface SpriteCoords {
  col: number
  row: number
}

export interface TileDefinition {
  id: number
  type: TileType
  name: string
  solid: boolean
  editorColour: string
  frames: BlobFrameSet
  baseCoords: SpriteCoords
}

// Named tile coordinate within a scene. Used to position the player on arrival.
export interface SpawnPoint {
  x: number
  y: number
}

// All spawn points for a map, keyed by local name (e.g. "entrance", "fromDungeon").
export type SpawnPoints = Record<string, SpawnPoint>

export const TILE_REGISTRY: readonly TileDefinition[] = [
${registryEntries},
]

// O(1) lookup. A tile ID not in the registry is a data bug — no silent fallback.
export function getTileById(id: number): TileDefinition {
  const def = TILE_REGISTRY[id]
  if (def === undefined) {
    throw new Error(\`Unknown tile id: \${id}. Valid range is 0–\${TILE_REGISTRY.length - 1}.\`)
  }
  return def
}
`
}

// ---------------------------------------------------------------------------
// packTilesheet

// Packs all frames into a fixed-grid PNG.
// Layout: one row per terrain type (ordered by registry index), frames left-to-right.
// Missing frames are left transparent. Minimum output is 1×1 if registry is empty.
export function packTilesheet(
  pixelData: FramePixelData,
  registry: readonly TileDefinition[],
): Buffer {
  const S = SPRITE_TILE_SIZE
  const numTypes = Math.max(1, registry.length)

  // Width: enough columns for the terrain type with the most frames, at least 1.
  const maxFrameCount = Math.max(
    1,
    ...registry.map((t) => pixelData[t.type]?.length ?? 0),
  )

  const width = maxFrameCount * S
  const height = numTypes * S

  const png = new PNG({ width, height })
  png.data.fill(0) // fully transparent by default

  for (let typeIdx = 0; typeIdx < registry.length; typeIdx++) {
    const tileDef = registry[typeIdx]
    const frames = pixelData[tileDef.type] ?? []

    for (let fi = 0; fi < frames.length; fi++) {
      const frame = frames[fi]
      for (let py = 0; py < S; py++) {
        for (let px = 0; px < S; px++) {
          const srcOffset = (py * S + px) * 4
          const dstX = fi * S + px
          const dstY = typeIdx * S + py
          const dstOffset = (dstY * width + dstX) * 4
          png.data[dstOffset] = frame[srcOffset] ?? 0
          png.data[dstOffset + 1] = frame[srcOffset + 1] ?? 0
          png.data[dstOffset + 2] = frame[srcOffset + 2] ?? 0
          png.data[dstOffset + 3] = frame[srcOffset + 3] ?? 0
        }
      }
    }
  }

  return PNG.sync.write(png)
}

// ---------------------------------------------------------------------------
// extractTilesheetPixels

// Extracts pixel data from an existing tilesheet PNG.
// Layout matches packTilesheet: one row per registry type, frames left-to-right.
// Used to merge authored types with existing data on partial export.
export function extractTilesheetPixels(
  pngBuffer: Buffer,
  registry: readonly TileDefinition[],
): FramePixelData {
  const S = SPRITE_TILE_SIZE
  const result: FramePixelData = {}

  let png: PNG
  try {
    png = PNG.sync.read(pngBuffer)
  } catch {
    return result
  }

  const width = png.width
  const height = png.height
  const framesPerRow = Math.floor(width / S)
  const numRows = Math.floor(height / S)

  for (
    let typeIdx = 0;
    typeIdx < Math.min(registry.length, numRows);
    typeIdx++
  ) {
    const tileDef = registry[typeIdx]
    const frames: number[][] = []

    for (let fi = 0; fi < framesPerRow; fi++) {
      const frame: number[] = []
      for (let py = 0; py < S; py++) {
        for (let px = 0; px < S; px++) {
          const srcX = fi * S + px
          const srcY = typeIdx * S + py
          const srcOffset = (srcY * width + srcX) * 4
          frame.push(
            png.data[srcOffset] ?? 0,
            png.data[srcOffset + 1] ?? 0,
            png.data[srcOffset + 2] ?? 0,
            png.data[srcOffset + 3] ?? 0,
          )
        }
      }
      frames.push(frame)
    }

    result[tileDef.type] = frames
  }

  return result
}
