// src/world/tiles.ts
// Generated by the tile editor — see documents/tile-editor-spec.md.
// Do not edit by hand; use the tile editor to update tile types and blob rulesets.

export const SPRITE_TILE_SIZE = 16

export type TileType = "grass" | "wall" | "water" | "road"

export interface BlobFrame {
  frameIndex: number
  flipX: boolean
  flipY: boolean
}

// Full cardinal blob ruleset. Keys 0–15: 4-bit bitmask (bit0=N, bit1=E, bit2=S, bit3=W).
export type BlobFrameSet = Record<number, BlobFrame>

// Grid-unit location on the tilesheet (multiply by SPRITE_TILE_SIZE for pixels).
export interface SpriteCoords {
  col: number
  row: number
}

export interface TileDefinition {
  id: number
  type: TileType
  name: string
  solid: boolean
  editorColour: string
  frames: BlobFrameSet
  baseCoords: SpriteCoords
}

// Named tile coordinate within a scene. Used to position the player on arrival.
export interface SpawnPoint {
  x: number
  y: number
}

// All spawn points for a map, keyed by local name (e.g. "entrance", "fromDungeon").
export type SpawnPoints = Record<string, SpawnPoint>

export const TILE_REGISTRY: readonly TileDefinition[] = [
  {
    id: 0,
    type: "grass",
    name: "Grass",
    solid: false,
    editorColour: "#4a7c3f",
    frames: {
      0: { frameIndex: 0, flipX: false, flipY: false },
      1: { frameIndex: 0, flipX: false, flipY: false },
      2: { frameIndex: 1, flipX: false, flipY: false },
      3: { frameIndex: 0, flipX: false, flipY: false },
      4: { frameIndex: 0, flipX: false, flipY: false },
      5: { frameIndex: 0, flipX: false, flipY: false },
      6: { frameIndex: 0, flipX: false, flipY: false },
      7: { frameIndex: 0, flipX: false, flipY: false },
      8: { frameIndex: 1, flipX: true, flipY: false },
      9: { frameIndex: 0, flipX: false, flipY: false },
      10: { frameIndex: 0, flipX: false, flipY: false },
      11: { frameIndex: 0, flipX: false, flipY: false },
      12: { frameIndex: 0, flipX: false, flipY: false },
      13: { frameIndex: 0, flipX: false, flipY: false },
      14: { frameIndex: 0, flipX: false, flipY: false },
      15: { frameIndex: 0, flipX: false, flipY: false },
    },
    baseCoords: { col: 0, row: 0 },
  },
  {
    id: 1,
    type: "wall",
    name: "Wall",
    solid: true,
    editorColour: "#5a5a5a",
    frames: {
      0: { frameIndex: 0, flipX: false, flipY: false },
      1: { frameIndex: 0, flipX: false, flipY: false },
      2: { frameIndex: 0, flipX: false, flipY: false },
      3: { frameIndex: 0, flipX: false, flipY: false },
      4: { frameIndex: 0, flipX: false, flipY: false },
      5: { frameIndex: 0, flipX: false, flipY: false },
      6: { frameIndex: 0, flipX: false, flipY: false },
      7: { frameIndex: 0, flipX: false, flipY: false },
      8: { frameIndex: 0, flipX: false, flipY: false },
      9: { frameIndex: 0, flipX: false, flipY: false },
      10: { frameIndex: 0, flipX: false, flipY: false },
      11: { frameIndex: 0, flipX: false, flipY: false },
      12: { frameIndex: 0, flipX: false, flipY: false },
      13: { frameIndex: 0, flipX: false, flipY: false },
      14: { frameIndex: 0, flipX: false, flipY: false },
      15: { frameIndex: 0, flipX: false, flipY: false },
    },
    baseCoords: { col: 0, row: 1 },
  },
  {
    id: 2,
    type: "water",
    name: "Water",
    solid: true,
    editorColour: "#3a6bc4",
    frames: {
      0: { frameIndex: 0, flipX: false, flipY: false },
      1: { frameIndex: 0, flipX: false, flipY: false },
      2: { frameIndex: 0, flipX: false, flipY: false },
      3: { frameIndex: 0, flipX: false, flipY: false },
      4: { frameIndex: 0, flipX: false, flipY: false },
      5: { frameIndex: 0, flipX: false, flipY: false },
      6: { frameIndex: 0, flipX: false, flipY: false },
      7: { frameIndex: 0, flipX: false, flipY: false },
      8: { frameIndex: 0, flipX: false, flipY: false },
      9: { frameIndex: 0, flipX: false, flipY: false },
      10: { frameIndex: 0, flipX: false, flipY: false },
      11: { frameIndex: 0, flipX: false, flipY: false },
      12: { frameIndex: 0, flipX: false, flipY: false },
      13: { frameIndex: 0, flipX: false, flipY: false },
      14: { frameIndex: 0, flipX: false, flipY: false },
      15: { frameIndex: 0, flipX: false, flipY: false },
    },
    baseCoords: { col: 0, row: 2 },
  },
  {
    id: 3,
    type: "road",
    name: "Road",
    solid: false,
    editorColour: "#8b6b4a",
    frames: {
      0: { frameIndex: 0, flipX: false, flipY: false },
      1: { frameIndex: 0, flipX: false, flipY: false },
      2: { frameIndex: 0, flipX: false, flipY: false },
      3: { frameIndex: 0, flipX: false, flipY: false },
      4: { frameIndex: 0, flipX: false, flipY: false },
      5: { frameIndex: 0, flipX: false, flipY: false },
      6: { frameIndex: 0, flipX: false, flipY: false },
      7: { frameIndex: 0, flipX: false, flipY: false },
      8: { frameIndex: 0, flipX: false, flipY: false },
      9: { frameIndex: 0, flipX: false, flipY: false },
      10: { frameIndex: 0, flipX: false, flipY: false },
      11: { frameIndex: 0, flipX: false, flipY: false },
      12: { frameIndex: 0, flipX: false, flipY: false },
      13: { frameIndex: 0, flipX: false, flipY: false },
      14: { frameIndex: 0, flipX: false, flipY: false },
      15: { frameIndex: 0, flipX: false, flipY: false },
    },
    baseCoords: { col: 0, row: 3 },
  },
]

// O(1) lookup. A tile ID not in the registry is a data bug — no silent fallback.
export function getTileById(id: number): TileDefinition {
  const def = TILE_REGISTRY[id]
  if (def === undefined) {
    throw new Error(`Unknown tile id: ${id}. Valid range is 0–${TILE_REGISTRY.length - 1}.`)
  }
  return def
}
